### ISSUE TITLE
颜色值强制不允许使用命名色值的疑问

### ISSUE THREAD

**Issue by gemwuu** [fex-team/styleguide#28]
文档地址：[颜色值强制不允许使用命名色值](https://github.com/fex-team/styleguide/blob/master/css.md#%E5%BC%BA%E5%88%B6-%E9%A2%9C%E8%89%B2%E5%80%BC%E4%B8%8D%E5%85%81%E8%AE%B8%E4%BD%BF%E7%94%A8%E5%91%BD%E5%90%8D%E8%89%B2%E5%80%BC)
想请问下你们强制不使用命名色值的考虑是什么?

**Comment by Dafrok** [comment]
没有参与过 styleguide 的讨论，但是我想有可能是出于兼容性考虑，毕竟 HTML5 之前 color keywords 只有 16 种

**Comment by gemwuu** [comment]
实际上业务里面也不太可能用更多的 keywords，因为不太好记。比如我可能常用的是 `white`、`black`、`red`，而不太会用 `lightblue`。单从大部分浏览器兼容的 16 个 keywords 讲，使用起来没有什么坏处，可读性更好。

**Comment by Dafrok** [comment]
以下仅代表个人观点：

include 和 smoosh 门的经验告诉我们，对 Web 而言可用性永远是第一位的

**Comment by gemwuu** [comment]
嗯。可用性是第一位的。考虑到 CSS 预处理，如果用 keywords 有被复写成其他值的风险。多谢解答。
